export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

export const FETCH_BOOK_BY_ID_START = 'FETCH_BOOK_BY_ID_START';
export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_SUCCESS';
export const FETCH_BOOK_BY_ID_FAIL = 'FETCH_BOOK_BY_ID_FAIL';

export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAIL = 'FETCH_COLLECTIONS_FAIL';

export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';

export const REMOVE_BOOK_FROM_CART = 'REMOVE_BOOK_FROM_CART';

export const INCREMENT_BOOK_QUANTITY = 'INCREMENT_BOOK_QUANTITY';
export const DECREMENT_BOOK_QUANTITY = 'DECREMENT_BOOK_QUANTITY';